services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: pablobhz
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/springmail
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge
volumes:
  db: